language: node_js
node_js:
  - "7"

# addons
#   apt
# cache
# env
# services

# Build Lifecycle
# 1. OPTIONAL Install apt addons
# 2. OPTIONAL Install cache components
# 3. before_install
# 4. install
# 5. before_script
# 6. script
script: 
  - npm run test
# 7. OPTIONAL before_cache ( for cleaning up cache )
# 8. after_success or after_failure:
# 9. OPTIONAL before_deploy
# 10. OPTIONAL deploy
# 11. OPTIONAL after_deploy
# 12. after_script